import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils"
// import { Open_Sans, Georgia, Meddon } from "next/font/google";

// const fontSans = Open_Sans({
//   subsets: ["latin"],
//   variable: "--font-sans",
// });

// const fontSerif = Georgia({
//   subsets: ["latin"],
//   variable: "--font-serif",
// });

// const fontMono = Menlo({
//   subsets: ["latin"],
//   variable: "--font-mono",
// });

export const metadata: Metadata = {
  title: "Next.js Hall of Heroes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // change type of letters
  return (
    <html
      lang="en"
      // className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} antialiased`}
      suppressHydrationWarning
    >
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
