import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/layout/theme-provider";
import { ViewTransitionListener } from "@/components/layout/ViewTransitionListener";
import { Suspense, ViewTransition } from "react"; // or 'next/view-transition'
import { ParamLoadingProvider } from "@/components/layout/ParamLoadingContext";

// import { Open_Sans, Georgia, Meddon } from "next/font/google";

// const fontSans = Open_Sans({
//   subsets: ["latin"],
//   variable: "--font-sans",
// });

// const fontSerif = Georgia({
//   subsets: ["latin"],
//   variable: "--font-serif",
// });

// const fontMono = Menlo({
//   subsets: ["latin"],
//   variable: "--font-mono",
// });

export const metadata: Metadata = {
  title: "Next.js Hall of Heroes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // change type of letters
  return (
    <html
      lang="en"
      // className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} antialiased`}
      suppressHydrationWarning
    >
      <body>
        <ParamLoadingProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Suspense fallback={null}>
              <ViewTransitionListener />
              <ViewTransition>
                {children}
              </ViewTransition>
            </Suspense>
          </ThemeProvider>
        </ParamLoadingProvider>
      </body>
    </html>
  );
}
